#!/usr/bin/with-contenv bash
set -e

# Check required arguments
if [ -z "$SMTP_LOGIN" -o -z "$SMTP_PASSWORD" ] ; then
	echo "SMTP_LOGIN and SMTP_PASSWORD must be defined, exiting..."
	exit 1
fi

# Get the two required values
export SMTP_LOGIN
export SMTP_PASSWORD

# Collect the rest or set default values
export EXT_RELAY_HOST=${EXT_RELAY_HOST:-"email-smtp.us-east-1.amazonaws.com"}
export EXT_RELAY_PORT=${EXT_RELAY_PORT:-"587"}
export RELAY_HOST_NAME=${RELAY_HOST_NAME:-"srv1.in.macdata.io"}
export ACCEPTED_NETWORKS=${ACCEPTED_NETWORKS:-"172.16.0.0/12 10.0.0.0/8"}
export USE_TLS=${USE_TLS:-"yes"}
export TLS_VERIFY=${TLS_VERIFY:-"may"}

# Set hostname for Postfix
echo $RELAY_HOST_NAME > /etc/mailname

# Generate Postfix configs from templates
j2 /conf/postfix-main.cf > /etc/postfix/main.cf
j2 /conf/sasl_passwd > /etc/postfix/sasl_passwd

# Hash the password file
postmap /etc/postfix/sasl_passwd
